name: Create Release and Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
  releases-matrix:
    needs: [create_release]
    name: Release Binaries
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            file: x2h
            args: --best --lzma
            strip: true
          #- os: windows-latest
          #  file: x2h.exe
          #  args: -9
          #  strip: false
          #- os: macos-latest
          #  file: x2h
          #  args: --best
          #  strip: true
    steps:
    - uses: actions/checkout@v4
   # - uses: graalvm/setup-graalvm@v1
   #   with:
   #     java-version: '21'
   #     distribution: 'graalvm'
   #     github-token: ${{ secrets.GITHUB_TOKEN }}
   #     native-image-job-reports: 'true'
   # - name: Build
   #   run: |
   #     gradle build
   #     native-image --no-fallback -jar build/libs/x2h.jar
   # - name: Compress binary
   #   uses: svenstaro/upx-action@v2
   #   with:
   #     file: ${{ matrix.file }}
   #     args: ${{ matrix.args }}
   #     strip: ${{ matrix.strip }}
    - name: Upload binary
      uses: skx/github-action-publish-binaries@release-2.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        releaseId: ${{ needs.create_release.outputs.id }}
        args: 'x2h*'


    # - name: Upload binary
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: x2h-${{ matrix.os }}
    #     path: x2h*
#${{ fromJSON(steps.create-release.outputs.id) }}
